platform :ios, '8.0'

inhibit_all_warnings!

target 'JwCompose' do
    
#pod 'AFNetworking'              //最新版本
#pod 'AFNetworking', '2.0'       //使用2.0的版本
#pod 'AFNetworking', '> 2.0'     //使用高于2.0的版本
#pod 'AFNetworking', '>=2.0'     //使用大于或等于2.0的版本
#pod 'AFNetworking', '< 2.0'     //使用小于2.0的版本
#pod 'AFNetworking', '<=2.0'     //使用小于或等于2.0的版本
#pod 'AFNetworking', '~>0.1.2'   //使用大于等于0.1.2但小于0.2的版本
#pod 'AFNetworking', '~>0.1'     //使用大于等于0.1但小于1.0的版本
#pod 'AFNetworking', '~>0'       //最新版本

pod 'SAMKeychain'
pod 'FCUUID'

pod 'UIAlertViewBlockExtension'
pod 'MBProgressHUD'
pod 'IQKeyboardManager'
pod 'SDCycleScrollView'

pod 'SDWebImage'
pod 'SDWebImage/GIF'
pod 'SDWebImage/WebP'
pod 'FLAnimatedImage'

pod 'PPGetAddressBook'
pod 'MJRefresh'
pod 'iCarousel'

pod 'AFNetworking'
pod 'JSONModel'
pod 'MJExtension'

pod 'FMDB'
pod 'GPUImage'
pod 'iCarousel'

pod 'LBXAlertAction'
pod 'LBXScan/LBXNative'
pod 'LBXScan/LBXZXing'
pod 'LBXScan/LBXZBar'
pod 'LBXScan/UI' 

pod 'YYModel'
pod 'YYCache'
pod 'YYImage'
pod 'YYWebImage'
pod 'YYText'
pod 'YYKeyboardManager'
pod 'YYDispatchQueuePool'
pod 'YYAsyncLayer'
pod 'YYCategories'

pod 'NSString-Hashes'
pod 'NSDate+TimeAgo'

pod 'Masonry'
pod 'pop'

pod 'JPush'
pod 'mob_sharesdk'
pod 'mob_sharesdk/ShareSDKUI'
pod 'mob_sharesdk/ShareSDKExtension'

pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
pod 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.1'
        end
    end
end

end
